### ISSUE TITLE
How to get TCN from iOS device

### ISSUE THREAD

**Issue by gnuhel** [TCNCoalition/tcn-client-android#21]
Hi, 

we are trying to use TCN protocol to track iOS and Android devices. iOS could retrieve TCN when advertising data from Android. But when iOS advertise the data, Android could not see any TCN data. Are we doing something wrong? We are using the implementation of Android and iOS in the repo.

In the doc it says
```
Android (Listener)	<=> iOS	 (SENDER)
The Listener signals availability as a Bluetooth peripheral. The Sender, acting as a Bluetooth central, connects to this peripheral and writes its TCN to a field exposed by the peripheral then disconnects.
```

So Android opens a GATTServer and iOS can write TCN to it. 

What happens if iOS is in the background? does it still try to write anything to the Android Gatt Server? I tried it but I didn't get anything? What would be the solution?

**Comment by romanpozd-tg17** [comment]
+1

**Comment by Zuhadather** [comment]
From iOS you can get only when the app is in foreground state not in background state.

only iOS two iOS can communicate when its in background mode.

**Comment by jennydove** [comment]
See https://github.com/TCNCoalition/TCN/issues/79 - closing this issue.
