### ISSUE TITLE
Add AlarmManager and setExactAndAllowWhileIdle() to work around Doze Mode

### ISSUE THREAD

**Issue by zssz** [TCNCoalition/tcn-client-android#9]
While testing the library with (https://github.com/covid19risk/covidwatch-android-minimal) I noticed that scanning and advertising stop around 15 minutes (USB cable pulled and screen locked), although the app was put on the battery optimization whitelist.

An idea to work around this issue to use AlarmManager and setExactAndAllowWhileIdle().

https://developer.android.com/training/monitoring-device-state/doze-standby

**Comment by prasad79** [comment]
https://developer.android.com/training/monitoring-device-state/doze-standby

On the above page there is a mention of:
"Note: Neither setAndAllowWhileIdle() nor setExactAndAllowWhileIdle() can fire alarms more than once per 9 minutes, per app."

Can this be avoided?

**Comment by zssz** [comment]
That's ok. We need to change the TCN every 15 minutes and no earlier.
